CREATE TABLE IF NOT EXISTS sigma.supervisor_evaluation (
    id SERIAL PRIMARY KEY,
    monitoring_id BIGINT NOT NULL REFERENCES sigma.monitoring(id),
    monitor_code VARCHAR(20) NOT NULL REFERENCES sigma.monitor(code),
    professor_id VARCHAR(255) NOT NULL REFERENCES sigma.professor(id),
    monitoring_monitor_id BIGINT REFERENCES sigma.monitoring_monitor(id),
    guidance_clarity INTEGER NOT NULL CHECK (guidance_clarity BETWEEN 1 AND 7),
    role_expectations INTEGER NOT NULL CHECK (role_expectations BETWEEN 1 AND 7),
    availability_disposition INTEGER NOT NULL CHECK (availability_disposition BETWEEN 1 AND 7),
    support_timeliness INTEGER NOT NULL CHECK (support_timeliness BETWEEN 1 AND 7),
    feedback_constructive INTEGER NOT NULL CHECK (feedback_constructive BETWEEN 1 AND 7),
    feedback_fairness INTEGER NOT NULL CHECK (feedback_fairness BETWEEN 1 AND 7),
    respectful_treatment INTEGER NOT NULL CHECK (respectful_treatment BETWEEN 1 AND 7),
    trust_environment INTEGER NOT NULL CHECK (trust_environment BETWEEN 1 AND 7),
    total_score NUMERIC(4,2) NOT NULL,
    performance_level VARCHAR(30) NOT NULL,
    strengths_comments TEXT,
    improvement_comments TEXT,
    submitted_by VARCHAR(50),
    semester VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_supervisor_eval UNIQUE (monitoring_id, monitor_code)
);
