# Choose between local or cloud (azure)
<<<<<<< HEAD
# spring.profiles.active=cloud 

spring.profiles.active=local
=======
spring.profiles.active=cloud 

# spring.profiles.active=local
>>>>>>> origin/dev
# Para el local, se necesita correr los scripts sql (no están en el repo)

